name: Deploy Serverless

on: [ push ]
jobs:
  build:
    name: Test and Build
    runs-on: macos-10.15
    timeout-minutes: 20
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup NVM and Node
        run: |
          curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.36.0/install.sh | bash
          export NVM_DIR=$HOME/.nvm
          source $NVM_DIR/nvm.sh
          nvm install
          echo '[ -s "$HOME/.bashrc" ] && \. "$HOME/.bashrc"' >> $HOME/.bash_profile
          node --version

      - name: Npm Install
        working-directory: ./src/lambda
        run: npm ci

      - name: Install Serverless
        if: github.ref == 'refs/heads/master'
        run: npm install -g serverless

      - name: Setup AWS CLI
        if: github.ref == 'refs/heads/master'
        uses: chrislennon/action-aws-cli@v1.1

      - name: Setup AWS Credentials
        if: github.ref == 'refs/heads/master'
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: us-west-1

#      - name: Setup Sentry
#        if: github.ref == 'refs/heads/master'
#        run: sed -i '' "s|XXX_SENTRY_DSN_XXX|${{ secrets.SENTRY_DSN }}|" src/lambda/handler.ts

      - name: Sls Deploy
        if: github.ref == 'refs/heads/master'
        working-directory: ./src/lambda
        run: sls deploy

